### ISSUE TITLE
reuse the create2 address to save gas

### ISSUE THREAD

**Issue by connbin** [FairCrypto/XENFT#13]
## reason

1. use "powerDown" to destroy the created address, each minting is the same gas consumption;
2. in terms of economic benefits, the lower the cost, the greater the competitive advantage. If the address is reused, the gas consumption will be reduced.

## gas used difference

- The address is not reused
first ClaimRank * 10: 1929000
second ClaimRank * 10: 1929000

- Address multiplexing
first ClaimRank * 10: 1929000
second ClaimRank * 10: 1536000

## other instructions

Adding address multiplexing will increase the complexity, just a suggestion.

**Comment by lbelyaev** [comment]
hey @connbin thanks for being part of XEN community and raising this topic. (sorry it took a while to respond)
it's a totally valid point and got similar results while testing, however reusing 'create2' addresses, or VMUs would require longer lifecycle of this 'infrastructure'. That would contradict with the lifecycle of XENFTs which are the cornerstone of XEN Torrent bulk minter. It gets redeemed and is not meant to be used again. Hence we clean up.
We might wanna release a pure 'utility' bulk minter though, where VMUs could be reused, saving gas.
Thanks again and let's keep in touch!
